### ISSUE TITLE
Text-input memory/element leak?

### ISSUE THREAD

**Issue by eugene1g** [nikgraf/belle#1]
Hi Nikgraf,

Cool branch off! One note - there might be a memory/element leak somewhere. I noticed that after typing in the demo textbox (http://nikgraf.github.io/belle/#text-input) my browser tends to go ballistic and adds hundreds of new DOM elements on key keystroke, which brings it to a halt and introduces a lengthy lag between keydown and character appearing on the screen. After a few lines document.getElementsByTagName('*') reporting 20,000 elements (vs 300 at the start).

I didn't have a chance to investigate whether the problem is with the textbox itself or the page wrapping or any external change listeners.

**Comment by nikgraf** [comment]
@eugene1g thanks a lot for the feedback. Which browser do you use? I can't reproduce it :(

**Comment by eugene1g** [comment]
Chrome42 - the screenshot is attached you can see node count (the blue line) jiggling up and down hitting 300k and then going back.

All I did was type in "one two three four five six seven eight nine ten eleven twelve"

![screen shot 2015-03-27 at 6 52 46 pm](https://cloud.githubusercontent.com/assets/147496/6864229/7d8625fa-d4b2-11e4-8e18-db1a6b93b7c3.png)

**Comment by nikgraf** [comment]
@eugene1g This screenshot was worth gold. Thanks :smile:
I did a bit of testing & now believe it's an issue of the valueLink functionality. Could you confirm?

Providing a defaultValue for the TextInput (new lines not allowed) results in this:

![screen shot 2015-03-29 at 07 10 25](https://cloud.githubusercontent.com/assets/223045/6883322/92c77b30-d5e3-11e4-9124-3250f87f2c93.png)

With new lines allowed you can see little spike which I believe are due the height calculation. The number of total nodes rised, but only by a handful.

![screen shot 2015-03-29 at 07 11 38](https://cloud.githubusercontent.com/assets/223045/6883328/bf5b1cb0-d5e3-11e4-9b68-3d7497fafb7a.png)


I tried valueLink first with a plain textarea & then with an input of type text and it resulted in a similar memory behaviour:

```
<input type="text" valueLink={ this.linkState('value') } />
```

![screen shot 2015-03-29 at 07 06 09](https://cloud.githubusercontent.com/assets/223045/6883331/d6e2ad6c-d5e3-11e4-9562-87000727cac8.png)

```
<textarea valueLink={ this.linkState('value') } placeholder="Just fill in whatever you like :)" />
```

![screen shot 2015-03-29 at 07 03 44](https://cloud.githubusercontent.com/assets/223045/6883337/f0df50d0-d5e3-11e4-9e86-362ab8fabbb5.png)

**Comment by eugene1g** [comment]
Perfect fix - no more leaks!

**Comment by nikgraf** [comment]
People still have issues here: https://www.reddit.com/r/reactjs/comments/3dh9k0/introducing_belle_100_easy_to_style_react/ct596fp

**Comment by jpuri** [comment]
Ya I just checked it there...

**Comment by jpuri** [comment]
I saw that in general controlled components in our docs are slowing down as we type more. But I came across this fiddle with controlled input and textarea components really fast: http://jsfiddle.net/f1v1fac1/

As I copied the same components in our docs, they also became slow, interesting :)

**Comment by jpuri** [comment]
Finding: in docs we are using highlightJs for highlighting the code. When we type a lot in controlled <TextInput> render is called multiple times and these code blocks are rendered again and again, this is adding crazy number of elements to dom and slowing down the page.

**Comment by nikgraf** [comment]
Solved with https://github.com/nikgraf/belle/pull/129

Really good find @jpuri
