### ISSUE TITLE
Fix rendering bug when switching themes

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#101]
Right now if you switch themes some styles seem to not be applied e.g. focusStyle on Rating

**Comment by jpuri** [comment]
The reason for this issue Nik is that pseudo classes we are injecting using 'injectStyles(styles);'.
In componentWillReceiveProps we should use have:
    removeStyle(this.ratingWrapperStyleId);

Before:
    updatePseudoClassStyle(this._styleId, properties, this.preventFocusStyleForTouchAndClick);

Let me fix this.

**Comment by jpuri** [comment]
I have created PR: https://github.com/nikgraf/belle/pull/103
There might be issues other than these also with styling, we can test more.

**Comment by nikgraf** [comment]
good find, unfortunately it's still a problem because pseudoClass styles are only updated in the constructor or willReceiveProperties. We just call render on theme switch right now. I'm not sure we even want to handle the case people changing the config on the fly properly. As an alternative we could have a query string in the route & based on this decide the theme. When someone changes the theme we switch the URL & do a window.location.reload()

**Comment by jpuri** [comment]
Yep we can fix issue in docs by using window.location.reload() and I think the probably of users changing themes on fly is very low.

But @nikgraf , if I think from the perspective of good code structure....if theme can change dynamically its  not good to bring them in react components with just 
```import style from '../style/button';```

Probably a design like this which Vjeux told would be better:

```belleComponents = new BelleComponents(stylingTheme)```

React component should ideally change only by user interaction or change in props..... this 'forceUpdate()' brings a feeling of something done wrong.

**Comment by jpuri** [comment]
This way to configuring by changing core configurations in lib do not look good:

belle.style.button.style = _.extend(belle.style.button.style, {
  color: '#FFF',
  background: '#444',
  border: '1px solid #444',
  borderBottomColor: '#000'
});

**Comment by nikgraf** [comment]
Hmmm, we can provide an extra API, but I had the feeling it's not necessary. The idea was that if we have simple plain JS objects then people are familiar with it & can overwrite or extend them depending on what they want.

**Comment by nikgraf** [comment]
I think this would still be nice, but we should stick to the commonJS API use-case that's what JS people are used to.

**Comment by nikgraf** [comment]
Fixed with this PR: https://github.com/nikgraf/belle/pull/109
