### ISSUE TITLE
toggle icon doesn't show

### ISSUE THREAD

**Issue by luisrudge** [nikgraf/belle#116]
I'm running chrome 43.0.2357.134m on windows.

![image](https://cloud.githubusercontent.com/assets/941075/8710191/6090b48e-2b1e-11e5-9c19-cf90cdcb0cfc.png)

**Comment by nikgraf** [comment]
@luisrudge oh, thx for point this out. What Windows version do you have?

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/8710922/c310cbda-2b23-11e5-9a50-51c5f715924f.png)

Latest windows10 build (10240)

**Comment by nikgraf** [comment]
Good to know. Might be better to use custom SVG icons in case Windows doesn't support certain unicode characters. /cc @jpuri

**Comment by luisrudge** [comment]
MS EDGE shows the icons just fine. They don't work on chrome. I messed up. Not sure why I sent a MS EDGE print screen :D
