### ISSUE TITLE
Examples are not running due to React dependency not being resolved 

### ISSUE THREAD

**Issue by alanrsoares** [nikgraf/belle#120]
```
clone belle
cd belle
npm install
cd examples
npm install
npm start
...
Error: Cannot find module 'react' from '~/dev/belle/lib/components'
[Error: write after end]
Error: Cannot find module 'react' from '~/dev/belle/lib/config'
[Error: write after end]
```

**Comment by jpuri** [comment]
Hey @alanrsoares ,

Please let us know specific OS you are using and whats your version on node/ npm.
Also can you try 'npm start' in belle directory before you do it in examples.

**Comment by alanrsoares** [comment]
Hi @jpuri 
I'm running on OSX Yosemite, node 0.12.0

**Comment by jpuri** [comment]
Do it in this sequence:

cd ~/belle
npm install
npm start

Now you will be able to see a lib directory inside belle directory, now do:

cd examples
npm install
npm start

Hope that will help and let us know if you still do not find any luck.

**Comment by alanrsoares** [comment]
Makes sense :)

**Comment by jpuri** [comment]
Another point to mention our test cases will not run with npm 0.12.0. Jest currently does not support it.

**Comment by jpuri** [comment]
Hey @alanrsoares,

I could find there was really some issue with package.json which we were not facing as our node_modules were already in place.

I have pushed a new commit to fix that, please take latest.

**Comment by alanrsoares** [comment]
Thank you. Indeed it wasn't working even after your instructions. I'll try
with the latest commits

**Comment by alanrsoares** [comment]
Working!

**Comment by jpuri** [comment]
Thanks for bringing this up :+1:

**Comment by nikgraf** [comment]
Great :smile:
