### ISSUE TITLE
New rules for development after the release?

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#127]
Decided:

**Comment by nikgraf** [comment]
Proposed rules:

- The next version is developed on the `develop` branch. I don't like the complexity of git flow, but it kind of makes sense for developing a library. http://nvie.com/posts/a-successful-git-branching-model/
- We still want to release often even if it's a small fix.
- We should have Changelog. Pull requests should update the changelog as well.
- Be there for questions in http://www.reactiflux.com/ (do we need Gitter then?)

Anything else?

**Comment by jpuri** [comment]
It would be nice to have some guidelines for contributors also.

**Comment by nikgraf** [comment]
+1 on the guidelines for contributors (e.g. git commit messages, code of conduct)
