### ISSUE TITLE
Exception thrown when using ComboBox component

### ISSUE THREAD

**Issue by alanrsoares** [nikgraf/belle#133]
```
Uncaught TypeError: Cannot read property 'cloneWithProps' of undefined(anonymous function) @ ComboBox.js:640
```

```javascript
import React from 'react';
import { ComboBox, Option } from 'belle';

export default class MyComponent extends React.Component {
  render() {
    return (
      <div>
        <ComboBox placeholder="foo">
          <Option value="foo">foo</Option>
          <Option value="bar">bar</Option>
        </ComboBox>
      </div>
    );
  }
}

```

PS.: Same exception is also thrown with the `Select` component.

**Comment by jpuri** [comment]
Seems like you are missing react addons. Check this: https://facebook.github.io/react/docs/addons.html

Please let us know if problem still persist.

**Comment by alanrsoares** [comment]
Thank you again, @jpuri. It was exactly that.
Should be updated in the docs though.

**Comment by jpuri** [comment]
Point noted :)
We will update docs.

**Comment by jpuri** [comment]
After merging the PR https://github.com/nikgraf/belle/pull/134. React.addons should not longer be a dependency.

**Comment by alanrsoares** [comment]
That's great news. You guys rock!
Looking forward to leave my contributions too.
