### ISSUE TITLE
Trigger onPressed/onUpdate without a 300ms delay

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#144]
Very often I see people doing onClick (which also gets triggered with touch and key board events).

When using touch events the onClick has a 300ms delay. To make it feel snappier we can trigger the onClick right after the touchEnd.

With an onPressed/onUpdate we could provide an optimised version that doesn't have a 300ms delay.

**Comment by jpuri** [comment]
I think it not very good idea to call 'props.onClick()' after touchEnd - it will be breaking the default behavior of onClick. I think it will be better to have onPressed, (onUpdate is typically for form elements as they update as result of user interaction).

But again our onPressed will be exactly same as onTouchEnd. Might be we can just leave a note in our docs about this behavior of onClick and onTouchEnd and which ones users should prefer.

@nikgraf , what do you suggest ?

**Comment by nikgraf** [comment]
@jpuri the 300ms delay was recently removed from webkit which means in future version the problem won't exist and we don't have to do anything about it :smile:
