### ISSUE TITLE
Fix using <Placeholder> and <Option> array together

### ISSUE THREAD

**Issue by andreychev** [nikgraf/belle#161]
```jsx
<Select value={ value } defaultValue={ defaultValue } onUpdate={ onChange } >
  <Placeholder>{ placeholder }</Placeholder>
  {
    options.map((o) => {
      return (<Option key={ o.id } value={ option.id } >{ option.name }</Option>);
    });
  }
</Select>
```

```javascript
Invalid children supplied to `Belle Select`, expected an Option or Placeholder component from Belle. Check the render method of `Dropdown`.
```

**Comment by nikgraf** [comment]
@andreychev thx for reporting, will look into this today or tomorrow

**Comment by jpuri** [comment]
Its coming from line: Select.jsx line:62
I guess issue is that when we use above way of giving options, the type is somehow not coming correct.

One trouble is also that options.map returns an array, placeholder has been given as separate component but should have been part of array.

placeholder + array !== array

**Comment by chrisvariety** [comment]
Workaround for now: `[<Placeholder>Foo bar</Placeholder>].concat(options.map(...))`

**Comment by jpuri** [comment]
This has been fixed with PR https://github.com/nikgraf/belle/pull/148
Soon there will be a release we well :)

**Comment by luisrudge** [comment]
any ETA on this PR? I just got bitten by this as well :)

**Comment by jpuri** [comment]
:) this should be merged and released in 1-2 days.

**Comment by nikgraf** [comment]
@luisrudge Will cut a release with this today :smile:

**Comment by nikgraf** [comment]
@andreychev we cut a release today - problem solved :smile:

**Comment by luisrudge** [comment]
Thanks @nikgraf and @jpuri!

**Comment by andreychev** [comment]
@nikgraf @jpuri good job, thx :)
