### ISSUE TITLE
belle + radium bug

### ISSUE THREAD

**Issue by luisrudge** [nikgraf/belle#170]
Not sure where's the problem, so I'm cross posting this in the two repos. [Radium repo](https://github.com/FormidableLabs/radium/issues/317)

When using Radium with Belle, I get this error: `Uncaught TypeError: iterable.forEach is not a function`

Here's the repro: https://github.com/luisrudge/belle-radium-bug

**Comment by jpuri** [comment]
I debug the issue in radium + belle, and it came out that out 2 components - Select / ComboBox are not working well with radium. These components are structured like:

```
<Select>
  <Placeholder>Select Country</Placeholder>
  <Option value="USA">USA</Option>
  <Option value="UK">UK</Option>
</Select>
```

Select code expects to get an array of the nested components in props.children:

<img width="231" alt="screen shot 2015-08-16 at 11 38 39 pm" src="https://cloud.githubusercontent.com/assets/2182307/9303519/30bad9d6-44fc-11e5-8c94-d5f23b82d906.png">

But with radium this array is converted to object:

<img width="259" alt="screen shot 2015-08-16 at 11 38 58 pm" src="https://cloud.githubusercontent.com/assets/2182307/9303527/43f2126c-44fc-11e5-97c3-20a06fe36273.png">

This is breaking the 2 components :(

**Comment by ianobermiller** [comment]
This isn't a Radium bug; belle should never manipulate this.props.children directly (e.g. by expecting it to be an array). Only the React.Children helpers should be used: https://facebook.github.io/react/docs/top-level-api.html#react.children.

(I mentioned the same thing in https://github.com/FormidableLabs/radium/issues/317)

**Comment by jpuri** [comment]
This makes sense, we will refactor our code for that. Thanks a lot @ianobermiller.

**Comment by luisrudge** [comment]
Thanks folks!

**Comment by jpuri** [comment]
Thanks a lot @luisrudge for bringing this up, we will soon fix it.

**Comment by luisrudge** [comment]
Thanks @jpuri Belle is amazing!

**Comment by ianobermiller** [comment]
:+1:

**Comment by nikgraf** [comment]
@jpuri I did some more investigation

With this code we get back this:

```
<Select>
  <Placeholder>-- Select a Fruit --</Placeholder>
  {
    map(fruits, (fruit, index) => {
      return (
        <Option value={ fruit.value }
                key={ index }>
          { fruit.content }
        </Option>
      );
    })
  }
</Select>
```

<img width="295" alt="screen shot 2015-08-25 at 03 00 49" src="https://cloud.githubusercontent.com/assets/223045/9456266/85ff40a6-4ad5-11e5-9ad4-848984be2b6d.png">

If we run map over them: `const children = React.Children.map(properties.children, (child) => child);` we get:

<img width="457" alt="screen shot 2015-08-25 at 03 01 33" src="https://cloud.githubusercontent.com/assets/223045/9456280/b1931fe4-4ad5-11e5-8c9a-ec89aad98451.png">

This is the same thing Radium provides us with. Right now it seems clear to me that we should work with objects like this one. I see two options right now:

1. modify Select, Combobox, Toggle and run `const children = React.Children.map(properties.children, (child) => child);` in the constructor of each of these components to make children consistent in their usage. We would need to update the helper functions. The downside here is that we unnecessarily iterate through the whole list.

2. update/add helper functions to be based on React.Children functions. We could build a filter specifically for React children components or a splice specifically for React children.

@jpuri To me options two seems like more work, but the proper implementation. What's your take?

**Comment by ianobermiller** [comment]
What are the use cases for filtering/splicing children? I don't even think you need to have children as an array for propTypes checks, as in `validateChildrenAreOptionsAndMaximumOnePlaceholder` (in `Select`), since you can just do the check while iterating using React.Children.forEach.

**Comment by jpuri** [comment]
Hey @ianobermiller ,
We still need filtering/ splicing in scenario like when user enters some test in combobox, we need options to be filtered.

@nikgraf , I would suggest writing new set of helper methods for filtering and other operations like some, index, first which will use React.Children.forEach underneath.
This may be little more code change, but I agree with you that's how we should so it.

**Comment by nikgraf** [comment]
@luisrudge @ianobermiller We fixed the issue and cut a new release. The newest version works well with Radium :smile:

**Comment by nikgraf** [comment]
@luisrudge @ianobermiller We fixed the issue and cut a new release. The newest version works well with Radium :smile:

**Comment by luisrudge** [comment]
Aweeeeeeeeesome! Thanks very much, all of you!
