### ISSUE TITLE
Select + children weirdness

### ISSUE THREAD

**Issue by luisrudge** [nikgraf/belle#172]
This works ok:

```
<Select>
    {[<Placeholder key="placeholder">Escolha uma seguradora</Placeholder>].concat(this.state.companiesWithTypeOfInsurance.map(c => <Option value={c.id}>{c.name}</Option>))}
</Select>
```
But this breaks the select component:
```
<Select>
  <Placeholder key="placeholder">Escolha uma seguradora</Placeholder>
  {this.state.companiesWithTypeOfInsurance.map(c => <Option value={c.id}>{c.name}</Option>)}
</Select>
```

This breaks the select component because, inside the Select component, this.props.children is like this: `{this.props.children:  [ReactElement, [ReactElement, ReactElement]]}`, so, when the code reaches [here](https://github.com/nikgraf/belle/blob/adbbe189df05c30d73be93f197c5df497dad6eaa/src/components/Select.jsx#L734), `entry` is actually an array of react elements and it throws an exception.

Is this a react problem? Or we should flatten the array before checking?

**Comment by luisrudge** [comment]
I'd like to fix this issue when someone agrees with me that there's an issue.

**Comment by luisrudge** [comment]
Damn. Totally dupe of #161. SOrry!

**Comment by nikgraf** [comment]
@luisrudge no worries, thanks for pointing out
