### ISSUE TITLE
Select, Combobox, do not expose standard events

### ISSUE THREAD

**Issue by Agamennon** [nikgraf/belle#188]
Select and Combobox should have props for onBlur , onChange, onFocus, and etc, so things like react form components can make use of it, as it stands it does not expose an "standards" api.

**Comment by nikgraf** [comment]
Hi @Agamennon, thanks for asking. In case we didn't miss anything we do expose all `onChange`, `onFocus` and so on. It's true that we don't expose onChange, but instead you can use `onUpdate`. This is, because simulating onChange properly would have increased component's complexity a lot and even React core contributors don't recommend it. See a longer explanation here: https://github.com/nikgraf/belle/issues/58/.

I would be happy to help you out. Maybe you can post an example of what you want to achieve and we can work it out together. Here an example using `onUpdate`:

```
<Select onUpdate={ (event) => console.log(event.value) }>
  <Option value={ "vienna" }>Vienna</Option>
  <Option value={ "rome" }>Rome</Option>
</Select>
```

**Comment by Agamennon** [comment]
I am trying to use [redux-forms](https://github.com/erikras/redux-form) , it uses the other standard events too, onUpdate is not enough, for instance i think `<TextInput />`  value propriety cannot be manipulated, so when a new value comes in it does not update. by the way you are doing a awesome work!

**Comment by jpuri** [comment]
Hey @Agamennon,

<TextInput /> value property can be manipulated, but if you use value property it becomes controlled component, check this for detailed explanation: http://nikgraf.github.io/belle/#/guide/form-components. Please let me know if that needs more clarity.

Belle supports most of standard events, can you please let us know which specific ones do you find missing.

**Comment by nikgraf** [comment]
@jpuri the missing onChange probably causes the problem. We could check if we can create a PR for redux-forms to also take onUpdate into account.

**Comment by jpuri** [comment]
Yeh ur right Nik, though a workaround could be that we call onChange from onUpdate.

**Comment by nikgraf** [comment]
@jpuri that's a good idea! We could mention it in the documentation as alias.

**Comment by jpuri** [comment]
Hey Nik,
Should we enhance our code to take care of onChange or should we suggest users to call onChange from onUpdate ?

**Comment by nikgraf** [comment]
I think it should be the same. So we need to fire onChange whenever onUpdate fires.

**Comment by nikgraf** [comment]
@jpuri Just opened an issue at redux-forms. I realised again that `onUpdate` looks differently than `onChange`.

**Comment by erikras** [comment]
@Agamennon, try `redux-form` [v1.7.0](https://github.com/erikras/redux-form/releases/tag/v1.7.0).

**Comment by nikgraf** [comment]
@Agamennon can you try it again? @erikras was so nice to add support for Belle's onUpdate.

**Comment by Agamennon** [comment]
@erikas @nikgraf, Thanks!,  will do, i am out of town up until next week, i will report back as soon as i come back.

**Comment by nikgraf** [comment]
@Agamennon any chance to give it a try?
