### ISSUE TITLE
is there something like roadmap about new components?

### ISSUE THREAD

**Issue by plandem** [nikgraf/belle#247]
I would like to stick with belle, but right now only few components :( What about at least others that you mentioned at 'Future Plans'?

p.s.: i would like to add 'grid' component, but don't know where to start from - i mean there is no any 'code standards'  that i must stick to contribute. any help?

**Comment by nikgraf** [comment]
hey @plandem - there is a bright future ahead for belle. From next January on I have 3 months full-time on open source and will spend a significant amount of time to work on belle.

I want to work on a new coding standard for belle 3.0.0 the week after this one. if you want to you could join a call and we start a grid component together that you can continue. What do you have in mind for a grid component. What kind of features?

Roadmap is something like:
- create the belle 3.0.0 coding standard
- create a test component (something simple)
- migrate all the components
- add a dropzone, navigation, dropdown, table (with sort)
- launch 3.0.0
- party hard :smile: 

keep in mind this is more or less a rough idea. feedback & help is very much appreciated

**Comment by plandem** [comment]
hey, it sounds great about 3 month of full time - really bright future.

1) about grid, i saw and try alot of js grids, but my experience tells me that in 80% you will need common table with sorting, paging, actions (e.g. last column with buttons), template for row/cell output, columns setup (e.g. cols/rowspan, multiline columns) and some kind of 'bulk actions' - like checkbox all rows and etc. 

2) Yes, often grids also needs a filter, but in most cases it's only at demo you can see built-in filter in columns, but in real world it almost useless and you will need more complex way to filter data, like few criteria for same attribute of model (with differ operand OR/AND). So in most cases i had to create from ground a external filter for grid and exclude built-in filters. So for that feature i would think about separate component with ability to "bind" to grid.

3) More advanced grids also let you to use some column settings, e.g.: resize, show/hide and etc, BUT it's like extra feature that can be missed, but not critical.

4) some advanced grids also let you inline editing, but my experience tells me that in real world, in most cases it's better to edit via external editor, maybe at modal window. 

5) server-side integration to get data from server

So i would like to stick with features from (1) and (5)

P.S.: of course serve-side integration for grid is must have feature.

P.P.S.: Ok, i will wait till draft of 3.0.0 and "test component" to join :)

**Comment by plandem** [comment]
Here is example of possible filter. That what i meant - it can be quite complex and 'built-in' simple filters will: a) not enough, b) quite ugly, c)not so easy to integrate with design

https://www.dropbox.com/s/ca6ky57t1zjcvy7/Screenshot%202015-12-07%2016.03.52.png?dl=0

**Comment by nikgraf** [comment]
this is super useful, let's chat next week :+1:

**Comment by jpuri** [comment]
Hey @plandem, nice research on grid. A data grid is something I would love making as well :smile:

**Comment by tonyxiao** [comment]
Do you have any plans to use something like Radium to handle inline styles rather than using the functions in `inject-style.js` file?

**Comment by nikgraf** [comment]
Hey @tonyxiao - yes indeed. From next week on I have a lot of time for Belle. @jpuri & I experimented with a future version of Belle to leverage different styling options like CSS Modules & JSS. See a first draft here: https://github.com/nikgraf/belle-future/tree/master/examples/components

**Comment by plandem** [comment]
i recommend to look at: https://github.com/ant-design/ant-design

i sticked to this library finally.

**Comment by luisrudge** [comment]
@plandem no english docs?

**Comment by plandem** [comment]
they are working on it. They just released v1.0 recently. But for me google translate and official site were enough:
http://ant.design/#/

**Comment by nikgraf** [comment]
The Ant components are beautiful. Glad you found something that works well for you 😃
