### ISSUE TITLE
inline styling

### ISSUE THREAD

**Issue by plandem** [nikgraf/belle#254]
what do you think?

http://jamesknelson.com/why-you-shouldnt-style-with-javascript/

**Comment by nikgraf** [comment]
Hi @plandem, we have thought about this a lot and most recently started an experiment to explore how Belle could evolve. If you have time feedback here is very much appreciated: https://github.com/nikgraf/future-react-ui/

**Comment by plandem** [comment]
done

**Comment by nikgraf** [comment]
thx :+1:
