### ISSUE TITLE
Combobox - Incorrect option selected when using filter?

### ISSUE THREAD

**Issue by kiresuah** [nikgraf/belle#269]
I am new to React/Belle but am experiencing an issue with the Combobox. I believe this is showing up in the documentation too.

When I set maxOptions and then begin typing into the input to sort through the options, the options are correctly sorted and displayed. However when I click on the option I have filtered down to, the incorrect option is put into the input.

So in the documentation on the currency example, if I begin typing "Egypt" into the box, it correctly sorts and finds the Egypt option: http://i.imgur.com/rrTMlB3.png

However when I click on Egypt, the Australia Dollar shows up in the box: http://i.imgur.com/ynPh6TO.png

It seems like it is simply picking in order - if the filtered option is third on the list, it picks the "Canada Dollar". If Fifth, the "Costa Rica Colon", etc.

I am not sure if I am doing something wrong with this or not, but I am getting the same behavior in my code with different data.

![image](https://cloud.githubusercontent.com/assets/17732472/14002544/0a91799e-f123-11e5-9add-fcf0cdc8c5b7.png)

![image](https://cloud.githubusercontent.com/assets/17732472/14002537/027297fc-f123-11e5-88d4-e3d3bfa2ad26.png)

**Comment by nikgraf** [comment]
@kiresuah you are absolutely right! Tomorrow I will have time to fix this and cut a new release right away!

Thanks for reporting

**Comment by nikgraf** [comment]
@kiresuah thanks again for reporting. Just release 2.0.5 with a fix.
