### ISSUE TITLE
Rating events misbehaving in OS X Safari 9

### ISSUE THREAD

**Issue by namuol** [nikgraf/belle#277]
Simple enough to reproduce; visit the [demo page for ratings](http://nikgraf.github.io/belle/#/component/rating) in Safari 9 and try clicking on a rating. The mouseover events work fine, but the click doesn't seem to register, and so the rating value doesn't persist.

**Comment by nikgraf** [comment]
I could reproduce the issue in Safari. Will look into this probably tomorrow. Thanks for letting us know :smile:

**Comment by nikgraf** [comment]
Sorry, took me a bit longer to get to it fixed here https://github.com/nikgraf/belle/issues/277 und cutting a new release now

**Comment by namuol** [comment]
Awesome! Thank you so much. :beers:
