### ISSUE TITLE
Spinner does not animate

### ISSUE THREAD

**Issue by mars** [nikgraf/belle#289]
Using Belle 2.0.7, I tried `<Spinner />` and it did not animate. [The docs](http://nikgraf.github.io/belle/#/component/spinner) don't mention anything except requiring the component and calling it in render.

After some research, I found that the keyframe animation `belle-spinner-pulse` is defined in `lib/style/animations` as an array of CSS rules. Eventually, I figured out the following `injectStyles` trick to get the animation to run:

``` javascript
import React from 'react';
import { Spinner } from 'belle';
import { injectStyles } from 'belle/lib/utils/inject-style';

class App extends React.Component {

  componentWillMount() {
    injectStyles([]);
  }

  render() {
    return (
      <div id="app-view">
        <Spinner />
      </div>
    );
  }
}

export default App;
```

Is this the intended method to load animations? I will make a documentation PR with this information, if it is correct.

Thanks for this sweet sweet component library :astonished:

**Comment by nikgraf** [comment]
Sorry for the late reply. You shouldn't need to do anything at all actually. Belle is taking care of injecting one style tag with the CSS by default.

import React from 'react';
import { Spinner } from 'belle';
import { injectStyles } from 'belle/lib/utils/inject-style';

```js
class App extends React.Component {
  render() {
    return (
      <div id="app-view">
        <Spinner />
      </div>
    );
  }
}

export default App;
```

Which platform & browser did you use?

**Comment by GenZai** [comment]
@mars Thanks your solution works for me.

**Comment by tconroy** [comment]
I'm unable to reproduce this issue on OSX/Chrome.

**Comment by GenZai** [comment]
@tconroy I'm using Meteor Framework, on Ubuntu 17.04 Firefox and chromium
