### ISSUE TITLE
React 15, Placerholder stopped working?

### ISSUE THREAD

**Issue by bradennapier** [nikgraf/belle#292]
Not sure but since updating to the newest version of React the Placeholder component for the select dropdown seems to have stopped functioning.

![image](https://cloud.githubusercontent.com/assets/15365418/14413306/ecce76bc-ff2a-11e5-8507-98d72ec74f26.png)

I don't appear to have access to the style or props necessary to fix this.  As far as I can tell, it is not rendering the Placeholder child at all. 

```
          <Select wrapperStyle={{width: '100%'}} shouldPositionOptions={false} menuStyle={menuStyle} {...fieldProps}>
            <Placeholder style={{minHeight: 45, height: 45, display: 'flex', alignItems: 'center'}}>
              {placeholder || 'Select One...'}
            </Placeholder>
            {renderedOptions}
          </Select>
```

**Comment by nikgraf** [comment]
Hey @bradennapier, sorry I was super busy finishing up 1.0 for https://www.draft-js-plugins.com/

I just gave it a try & couldn't reproduce the issue …

```js
<h3>Select placeholder test</h3>
<Select wrapperStyle={{ width: '100%' }} shouldPositionOptions={false}>
  <Placeholder>
    {'Select One...'}
  </Placeholder>
  <Option value={ 0 }>Zero</Option>
  <Option value={ 1 }>One</Option>
</Select>
```

<img width="354" alt="screen shot 2016-04-20 at 20 01 46" src="https://cloud.githubusercontent.com/assets/223045/14696783/bcc6fc0e-0732-11e6-9b88-9ab7a4c7dc48.png">
