### ISSUE TITLE
Is this component dead then?

### ISSUE THREAD

**Issue by bradennapier** [nikgraf/belle#320]
No updates in quite awhile and it appears the entire package is going to stop working on the next major react version?

![image](https://cloud.githubusercontent.com/assets/15365418/17718192/665b88de-63c7-11e6-86cf-12ae9c109e67.png)

**Comment by Bunkerbewohner** [comment]
I don't know about more updates, but imho we don't have to worry about that warning. The code that uses the PropTypes validation is there only to print more helpful error messages (it's a custom PropType validator using the built-in ones). So worst case that part is removed and you get the "plain" React error messages when passing wrong arguments to components.

**Comment by nikgraf** [comment]
sorry, been busy with too many project lately. I will cut a new release with these fixes. If someone is interested to contribute more and maintain please ping me.
