### ISSUE TITLE
use prop-types instead React.PropTypes

### ISSUE THREAD

**Issue by rohmanhm** [nikgraf/belle#339]
This morning I've tried to use your lib, but I got warning in my console.
> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

`React.PropTypes` is deprecated as of React v15.5. Please use the [`prop-types`](https://www.npmjs.com/package/prop-types) library instead.

Reference: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by nikgraf** [comment]
@rohmanhm good point, interested to create a PR?

**Comment by elazzabi** [comment]
I'll take this

**Comment by tconroy** [comment]
@nikgraf: https://github.com/nikgraf/belle/pull/341
