### ISSUE TITLE
Consistent Caret API & behaviour

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#51]
Would be good if both behave the same way. Let's see if there is a good path towards that goal.

**Comment by jpuri** [comment]
I think we should fix this one in this week itself (before we release).

**Comment by jpuri** [comment]
I think we can go we span caret as in Select right now.

Also is there some way that we had a tag conditionally in what we return from render() method (rather than using display:none to hide the element).

**Comment by jpuri** [comment]
As me and Nik discussed we will use span for caret (as used in select currently).
The api for ComboBox will be aligned to select.

**Comment by jpuri** [comment]
Done PR: https://github.com/nikgraf/belle/pull/91
