### ISSUE TITLE
Switch to webpack

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#54]

**Comment by jpuri** [comment]
+1, I have also been thinking about this.

**Comment by nikgraf** [comment]
Let's just do it. I want hot reload of components :smile:

**Comment by nikgraf** [comment]
https://github.com/gaearon/library-boilerplate

**Comment by nikgraf** [comment]
Done with this Pull-Request https://github.com/nikgraf/belle/pull/183
