### ISSUE TITLE
Deprecate Focus animation?

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#57]
This feature was really a bold move & there are still some issues. Question is if we should deprecate it at all.

**Comment by jpuri** [comment]
I think we can make it configurable and give user choice between plain (blue outline) focus style and our current animated focus style. Like what we are doing with this option "preventFocusStyleForTouchAndClick".

We will still live with complexity that this style handling bring to components. But I think there might be use cases where someone wants these animated focus styles or focusStyle hidden when you click.

And good UX comes with complexity cost :)

**Comment by ericmatthys** [comment]
In general, I find the "one time" focus animation to be visually interesting at the cost of accessibility. It's too easy to lose track of what is focused when the style doesn't stick around.

**Comment by jpuri** [comment]
Yep... we kind of felt that while we were writing those styles... thats is why we kept it so configurable. Those are default styles but you can always turn them off. Check out components on this link with classical focus styles:

http://nikgraf.github.io/belle/#/configuration?theme=belle-with-default-focus

**Comment by ericmatthys** [comment]
I think accessibility should be promoted by making this behavior the default and save the flair to be shown off in a theme. Otherwise, it could be seen as encouraging questionable practices. The configurability to allow either is definitely nice though.

**Comment by jpuri** [comment]
I agree with what you are saying, we always had that in our mind and thats the reason we created this issue :)
We will rethink about it and would let you know how we plan to handle this accessibility issue, which we agree exist with focus animation.

**Comment by jpuri** [comment]
Another possible downside of focus animation (of the kind we have right now in belle theme) is if we use button in button group or menu this can effect nearby component in the layout.

**Comment by jpuri** [comment]
Another important, tough minor thing that I noticed is that if we disable focus for touchAndClick, ideally we should disable focus when context menu opens.

There is another small issue, if you right click(open context) of an unfocused component focus animation will appear, but if you open contextMenu of an already focused element - no animation appears. Coz though focus is an extended state, current animated focus styles does not reflect that.

A possible style could be animation focus which does not completely fades away. (But this will create issue like one that comes when user switches between tabs and preventFocusStyleForTouchAndClick is true).
