### ISSUE TITLE
Align API for Toggle with the other components (value instead of checked)

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#61]
We used checked as it made sense to mimic the checkbox API. Since we are moving to onUpdate it's better to align the APIs & use value instead.

**Comment by nikgraf** [comment]
Closed with this PR https://github.com/nikgraf/belle/pull/63

**Comment by jpuri** [comment]
What are the down side of using "checked" with "onUpdate".

**Comment by nikgraf** [comment]
@jpuri only that the API becomes consistent between all Belle components

**Comment by jpuri** [comment]
HTML did not kept for this consistence across various tags... :)

**Comment by nikgraf** [comment]
I see it as a chance to do better than HTML :)

**Comment by jpuri** [comment]
:+1:
