### ISSUE TITLE
On iPhone you can't fill in text into the ComboBox input field

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#68]

**Comment by jpuri** [comment]
Strange its working bad in iPhone but works well on my android and also chrome (in mobile iPhone mode)

**Comment by jpuri** [comment]
Fixed by removing these styles for combobox box Input:

   WebkitUserSelect: 'none',
   MozUserSelect: 'none',
   MsUserSelect: 'none',
   userSelect: 'none',

**Comment by nikgraf** [comment]
yay :)
