### ISSUE TITLE
When leaving the target while touchStart or mouseDown the active state should be disabled

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#70]

**Comment by nikgraf** [comment]
A related issue is that when doing a Ctrl+Click to show the context menu the active state never goes away.

The solution might look similar as in: https://github.com/nikgraf/belle/pull/97

**Comment by nikgraf** [comment]
It was more of an idea. If you press the mouseDown on a button & then move away without leaving it would be great to indicate that if you release the mouse outside the click won’t be triggered (by removing the active state)

**Comment by nikgraf** [comment]
Might still be valid for touch events.

**Comment by nikgraf** [comment]
Not sure if we should do this as it breaks with default active state behaviour.

**Comment by jpuri** [comment]
Hey @nikgraf ,

I would say lets not do this. I was also thinking about it but then it would break active state behavior and expectations of users.

But still we need to fix issues with Rating, Button, Select, Toggle (if any), to make sure:
1. Active/ Focus state is not triggered when context menu is opened.
2. If mouseDown or touchStart happens at component and mouseUp / touchEnd happens outside - focusState, activeState should be reset.

**Comment by nikgraf** [comment]
I think we can close it :)
