### ISSUE TITLE
Rating Bug

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#80]
@jpuri I noticed when clicking mouseDown on a star of the Rating component, then drag & release somewhere else the stars are not set. Not even the old value is there.

Short demo video: https://youtu.be/8ZxPsG4KMj0

**Comment by jpuri** [comment]
I am not able to replicate this Nik. We can check this on ur screen whenever you get time.

**Comment by nikgraf** [comment]
@jpuri I'm looking into this now

**Comment by nikgraf** [comment]
Fixed with this PR: https://github.com/nikgraf/belle/pull/97
