### ISSUE TITLE
Propose a new styling API for Rating

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#86]
Originally this came up in this discussion: https://github.com/nikgraf/belle/issues/60

**Comment by nikgraf** [comment]
Solved with this PR: https://github.com/nikgraf/belle/pull/87

**Comment by nikgraf** [comment]
Closed the wrong issue

**Comment by jpuri** [comment]
PR: https://github.com/nikgraf/belle/pull/90 and code changed for this.
