### ISSUE TITLE
Active Style for ComboBox

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#89]
When a user does a mouseDown or touchStart at the ComboBox we should provide an activeStyle. While this is not necessary for the default belle styling we have right now it is for different themes e.g Bootstrap.

**Comment by jpuri** [comment]
Hey Nik,

While I am implementing the changes for combobox. I think duration when an input is active is effectively same as when its focused. Do we really need a separate activeStyle ?

**Comment by nikgraf** [comment]
Right, there is no point in doing so. Let's close this one.
