### ISSUE TITLE
Investigate if we can deprecate underscore

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/belle#96]
While a lot of people use underscore, some use lowdash or just go with ImmutableJS. In order to pre-subscribe belle users to underscore we might want to create little micro library only with the functions we really need. 

Proposed way of tackling this:

1. Collect all the functions we use
2. Copy them from underscore into a microlib and use this lib instead

**Comment by jpuri** [comment]
+1, good idea

**Comment by jpuri** [comment]
Also investigate if we can effectively use ES6 destructuring assignment in place on omit function.

**Comment by nikgraf** [comment]
:+1: looking forward to this

**Comment by nikgraf** [comment]
We included underscore. In the future we will refactor this part & take only what we need. https://github.com/nikgraf/belle/pull/108
